# fly.toml app configuration file generated for guess-app on 2023-07-14T17:05:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "guess-app"
primary_region = "atl"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
