# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)

steps:
  - task: SonarCloudPrepare@1
    displayName: "Setup sonarCloud"
    inputs:
      SonarCloud: "IdSonarCloud"
      organization: "applabs01"
      scannerMode: "CLI"
      configMode: "manual"
      cliProjectKey: "applabs01_guess-app"
      cliSources: "."

  - task: SonarCloudAnalyze@1
    displayName: "Run sonarCloud analysis"
    inputs:
      jdkversion: "JAVA_HOME_11_X64"

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"

  - task: Docker@2
    displayName: "Build and push image"
    inputs:
      containerRegistry: "ismaeldcent04-dockerhub"
      repository: "ismaeldcent04 / guess-app"
      command: "buildAndPush"
      Dockerfile: "starter/Dockerfile"
      tags: "$(tag)"

  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: "mySnyk"
      testType: "container"
      dockerImageName: "ismaeldcent04/guess-app:$(Build.BuildId)"
      dockerfilePath: "starter/Dockerfile"
      monitorWhen: "always"
      failOnIssues: false
